from __future__ import annotations

import json
import time
import uuid
from typing import Any
from ..gene_database import GeneDatabase, GeneRecord, ProteinDomain, PathwayRecord, OntologyNode


def _build_gene(
    gene_id: str,
    symbol: str,
    name: str,
    chromosome: str,
    start: int,
    end: int,
    summary: str,
    go_terms: list[dict[str, str]],
    pathways: list[dict[str, str]],
    domains: list[dict[str, str]],
    diseases: list[dict[str, str]],
    sequence_aa: str = "",
    sequence_nt: str = "",
    gene_type: str = "protein_coding",
    strand: str = "+",
    aliases: list[str] | None = None,
) -> GeneRecord:
    return GeneRecord(
        gene_id=gene_id,
        symbol=symbol,
        name=name,
        aliases=json.dumps(aliases or [], ensure_ascii=False),
        chromosome=chromosome,
        start_pos=start,
        end_pos=end,
        strand=strand,
        gene_type=gene_type,
        summary=summary,
        go_terms_json=json.dumps(go_terms, ensure_ascii=False),
        pathways_json=json.dumps(pathways, ensure_ascii=False),
        domains_json=json.dumps(domains, ensure_ascii=False),
        diseases_json=json.dumps(diseases, ensure_ascii=False),
        sequence_nt=sequence_nt,
        sequence_aa=sequence_aa,
    )


def _build_domain(domain_id: str, accession: str, name: str, description: str, source: str = "Pfam", consensus: str = "") -> ProteinDomain:
    return ProteinDomain(
        domain_id=domain_id,
        accession=accession,
        name=name,
        description=description,
        source_db=source,
        consensus_sequence=consensus,
    )


def _build_pathway(pathway_id: str, name: str, description: str, gene_ids: list[str], source: str = "KEGG") -> PathwayRecord:
    return PathwayRecord(
        pathway_id=pathway_id,
        name=name,
        source_db=source,
        description=description,
        gene_ids_json=json.dumps(gene_ids, ensure_ascii=False),
    )


SEED_GENES: list[GeneRecord] = [
    _build_gene(
        "ENSG00000141510", "TP53", "Tumor Protein P53", "17", 7668421, 7687550,
        "关键的肿瘤抑制因子和转录因子，调控细胞周期停滞、DNA修复、凋亡和衰老。响应DNA损伤、癌基因激活等应激信号。被称为'基因组守护者'。",
        [
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "p53 binding", "namespace": "molecular_function"},
            {"name": "regulation of cell cycle", "namespace": "biological_process"},
            {"name": "DNA damage response", "namespace": "biological_process"},
            {"name": "apoptotic process", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
            {"name": "mitochondrion", "namespace": "cellular_component"},
        ],
        [{"name": "Cell cycle", "pathway": "hsa04110"}, {"name": "p53 signaling pathway", "pathway": "hsa04115"}, {"name": "Apoptosis", "pathway": "hsa04210"}],
        [{"name": "P53 DNA-binding domain", "accession": "PF00870"}, {"name": "P53 tetramerization", "accession": "PF07710"}],
        [{"name": "Li-Fraumeni syndrome"}, {"name": "Multiple cancer types"}, {"name": "Osteosarcoma"}],
    ),
    _build_gene(
        "ENSG00000133703", "KRAS", "Kirsten Rat Sarcoma Viral Oncogene Homolog", "12", 25205246, 25250929,
        "GTPase小G蛋白，作为分子开关调控MAPK/ERK信号通路。控制细胞增殖、分化和存活。在多种癌症中高频突变(G12D, G12V, G13D)。",
        [
            {"name": "GTPase activity", "namespace": "molecular_function"},
            {"name": "GDP binding", "namespace": "molecular_function"},
            {"name": "RAS signal transduction", "namespace": "biological_process"},
            {"name": "cell proliferation", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "MAPK signaling pathway", "pathway": "hsa04010"}, {"name": "Ras signaling pathway", "pathway": "hsa04014"}, {"name": "PI3K-Akt signaling pathway", "pathway": "hsa04151"}],
        [{"name": "Ras GTPase", "accession": "PF00071"}],
        [{"name": "Pancreatic cancer"}, {"name": "Colorectal cancer"}, {"name": "Lung adenocarcinoma"}, {"name": "Noonan syndrome"}],
    ),
    _build_gene(
        "ENSG00000121879", "PIK3CA", "Phosphatidylinositol-4,5-Bisphosphate 3-Kinase Catalytic Subunit Alpha", "3", 179148114, 179240093,
        "PI3K催化亚基p110α，磷酸化PIP2生成PIP3，激活AKT-mTOR促生长信号通路。在乳腺癌、结肠癌等多种癌症中高频激活突变。",
        [
            {"name": "phosphatidylinositol 3-kinase activity", "namespace": "molecular_function"},
            {"name": "protein kinase activity", "namespace": "molecular_function"},
            {"name": "signal transduction", "namespace": "biological_process"},
            {"name": "positive regulation of cell proliferation", "namespace": "biological_process"},
            {"name": "cytosol", "namespace": "cellular_component"},
        ],
        [{"name": "PI3K-Akt signaling pathway", "pathway": "hsa04151"}, {"name": "mTOR signaling pathway", "pathway": "hsa04150"}, {"name": "EGFR tyrosine kinase inhibitor resistance", "pathway": "hsa01521"}],
        [{"name": "PI3K p85-binding domain", "accession": "PF02192"}, {"name": "PI3K catalytic domain", "accession": "PF00454"}, {"name": "PI3K lipid kinase", "accession": "PF00794"}],
        [{"name": "Breast cancer"}, {"name": "Colorectal cancer"}, {"name": "Gastric cancer"}, {"name": "PIK3CA-related overgrowth spectrum"}],
    ),
    _build_gene(
        "ENSG00000142208", "AKT1", "AKT Serine/Threonine Kinase 1", "14", 104769349, 104795751,
        "丝氨酸/苏氨酸蛋白激酶AKT（PKB）。核心促存活激酶，磷酸化并调控多种底物，控制细胞代谢、生长、增殖、存活和血管生成。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "intracellular signal transduction", "namespace": "biological_process"},
            {"name": "positive regulation of cell growth", "namespace": "biological_process"},
            {"name": "glucose metabolic process", "namespace": "biological_process"},
            {"name": "nucleoplasm", "namespace": "cellular_component"},
        ],
        [{"name": "PI3K-Akt signaling pathway", "pathway": "hsa04151"}, {"name": "mTOR signaling pathway", "pathway": "hsa04150"}, {"name": "FoxO signaling pathway", "pathway": "hsa04068"}, {"name": "Insulin signaling pathway", "pathway": "hsa04910"}],
        [{"name": "PH domain", "accession": "PF00169"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Proteus syndrome"}, {"name": "Cowden syndrome"}],
    ),
    _build_gene(
        "ENSG00000139618", "BRCA1", "Breast Cancer Type 1 Susceptibility Protein", "17", 43044295, 43170245,
        "DNA损伤修复蛋白，在DNA双链断裂的同源重组修复中发挥核心作用。与BRCA2和RAD51协同。突变显著增加乳腺癌和卵巢癌风险。",
        [
            {"name": "damaged DNA binding", "namespace": "molecular_function"},
            {"name": "ubiquitin-protein transferase activity", "namespace": "molecular_function"},
            {"name": "DNA repair", "namespace": "biological_process"},
            {"name": "cell cycle checkpoint", "namespace": "biological_process"},
            {"name": "chromosome", "namespace": "cellular_component"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Homologous recombination", "pathway": "hsa03440"}, {"name": "Fanconi anemia pathway", "pathway": "hsa03460"}],
        [{"name": "BRCA1 RING finger", "accession": "PF00097"}, {"name": "BRCA1 C-terminal (BRCT)", "accession": "PF00533"}],
        [{"name": "Hereditary breast and ovarian cancer"}, {"name": "Fanconi anemia"}],
    ),
    _build_gene(
        "ENSG00000012048", "BRCA2", "Breast Cancer Type 2 Susceptibility Protein", "13", 32315474, 32400266,
        "DNA修复蛋白，辅助RAD51在DNA双链断裂位点的装载，促进同源重组修复。突变导致基因组不稳定和癌症易感性。",
        [
            {"name": "single-stranded DNA binding", "namespace": "molecular_function"},
            {"name": "RAD51 binding", "namespace": "molecular_function"},
            {"name": "DNA repair", "namespace": "biological_process"},
            {"name": "sister chromatid cohesion", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Homologous recombination", "pathway": "hsa03440"}, {"name": "Fanconi anemia pathway", "pathway": "hsa03460"}],
        [{"name": "BRCA2 repeat", "accession": "PF00634"}, {"name": "BRCA2 OB-like", "accession": "PF09104"}],
        [{"name": "Hereditary breast and ovarian cancer"}, {"name": "Fanconi anemia"}, {"name": "Pancreatic cancer"}],
    ),
    _build_gene(
        "ENSG00000091831", "ESR1", "Estrogen Receptor 1", "6", 151656672, 152129619,
        "雌激素受体α，核受体超家族成员。被雌二醇激活后作为转录因子调控靶基因表达。控制女性生殖发育、骨密度、心血管保护。",
        [
            {"name": "estrogen receptor activity", "namespace": "molecular_function"},
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "steroid hormone mediated signaling pathway", "namespace": "biological_process"},
            {"name": "mammary gland development", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "Estrogen signaling pathway", "pathway": "hsa04915"}, {"name": "Breast cancer", "pathway": "hsa05224"}],
        [{"name": "Nuclear hormone receptor", "accession": "PF00104"}, {"name": "Estrogen receptor activation", "accession": "PF02161"}],
        [{"name": "Breast cancer"}, {"name": "Endometrial cancer"}, {"name": "Osteoporosis"}],
    ),
    _build_gene(
        "ENSG00000169083", "AR", "Androgen Receptor", "X", 67544021, 67730619,
        "雄激素受体，被睾酮/二氢睾酮激活的核受体转录因子。控制男性性征发育、精子发生、肌肉生长和前列腺功能。",
        [
            {"name": "androgen receptor activity", "namespace": "molecular_function"},
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "male sex determination", "namespace": "biological_process"},
            {"name": "prostate gland growth", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Prostate cancer", "pathway": "hsa05215"}, {"name": "Pathways in cancer", "pathway": "hsa05200"}],
        [{"name": "Nuclear hormone receptor", "accession": "PF00104"}, {"name": "Androgen receptor activation", "accession": "PF02161"}],
        [{"name": "Androgen insensitivity syndrome"}, {"name": "Prostate cancer"}, {"name": "Spinal and bulbar muscular atrophy"}],
    ),
    _build_gene(
        "ENSG00000141736", "ERBB2", "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)", "17", 39688094, 39728660,
        "EGFR家族受体酪氨酸激酶HER2，没有已知配体但组成型二聚化活性。通过RAS-MAPK和PI3K-AKT通路驱动细胞增殖。乳腺癌关键驱动基因。",
        [
            {"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "signal transduction", "namespace": "biological_process"},
            {"name": "positive regulation of cell proliferation", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "EGFR tyrosine kinase inhibitor resistance", "pathway": "hsa01521"}, {"name": "ErbB signaling pathway", "pathway": "hsa04012"}, {"name": "PI3K-Akt signaling pathway", "pathway": "hsa04151"}],
        [{"name": "Receptor tyrosine kinase", "accession": "PF07714"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "HER2-positive breast cancer"}, {"name": "Gastric cancer"}, {"name": "Ovarian cancer"}],
    ),
    _build_gene(
        "ENSG00000198793", "MTOR", "Mechanistic Target of Rapamycin Kinase", "1", 11106535, 11262551,
        "丝氨酸/苏氨酸蛋白激酶mTOR，作为mTORC1和mTORC2复合物的催化核心。整合营养、生长因子、能量和应激信号，调控蛋白合成、自噬、脂质合成和细胞骨架。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "regulation of cell growth", "namespace": "biological_process"},
            {"name": "positive regulation of translation", "namespace": "biological_process"},
            {"name": "TORC1 complex", "namespace": "cellular_component"},
            {"name": "lysosomal membrane", "namespace": "cellular_component"},
        ],
        [{"name": "mTOR signaling pathway", "pathway": "hsa04150"}, {"name": "PI3K-Akt signaling pathway", "pathway": "hsa04151"}, {"name": "Autophagy", "pathway": "hsa04140"}, {"name": "AMPK signaling pathway", "pathway": "hsa04152"}],
        [{"name": "FAT domain", "accession": "PF02259"}, {"name": "PI3K/PI4K kinase", "accession": "PF00454"}, {"name": "FATC domain", "accession": "PF02260"}],
        [{"name": "Cancer (various)"}, {"name": "Tuberous sclerosis"}, {"name": "Focal cortical dysplasia"}],
    ),
    _build_gene(
        "ENSG00000146648", "EGFR", "Epidermal Growth Factor Receptor", "7", 55019017, 55211627,
        "表皮生长因子受体，受体酪氨酸激酶。被EGF/TGFα激活后二聚化并自磷酸化，激活RAS-RAF-MEK-ERK和PI3K-AKT通路。肺癌重要驱动基因。",
        [
            {"name": "epidermal growth factor receptor activity", "namespace": "molecular_function"},
            {"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"},
            {"name": "signal transduction", "namespace": "biological_process"},
            {"name": "epidermal growth factor signaling pathway", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "EGFR tyrosine kinase inhibitor resistance", "pathway": "hsa01521"}, {"name": "ErbB signaling pathway", "pathway": "hsa04012"}, {"name": "MAPK signaling pathway", "pathway": "hsa04010"}],
        [{"name": "Receptor tyrosine kinase", "accession": "PF07714"}, {"name": "Furin-like cysteine-rich", "accession": "PF00757"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Non-small cell lung cancer (EGFR mutations)"}, {"name": "Glioblastoma"}, {"name": "Colorectal cancer"}],
    ),
    _build_gene(
        "ENSG00000157764", "BRAF", "B-Raf Proto-Oncogene Serine/Threonine Kinase", "7", 140719327, 140924929,
        "RAF家族丝氨酸/苏氨酸激酶，RAS-GTP下游核心效应器。磷酸化并激活MEK1/2，传导MAPK信号。V600E是最常见的致癌突变。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "MAP kinase kinase kinase activity", "namespace": "molecular_function"},
            {"name": "regulation of ERK1 and ERK2 cascade", "namespace": "biological_process"},
            {"name": "positive regulation of cell population proliferation", "namespace": "biological_process"},
            {"name": "cytosol", "namespace": "cellular_component"},
        ],
        [{"name": "MAPK signaling pathway", "pathway": "hsa04010"}, {"name": "Ras signaling pathway", "pathway": "hsa04014"}, {"name": "Melanoma", "pathway": "hsa05218"}],
        [{"name": "Protein kinase domain", "accession": "PF00069"}, {"name": "Raf-like Ras-binding domain", "accession": "PF02196"}],
        [{"name": "Melanoma (BRAF V600E)"}, {"name": "Colorectal cancer"}, {"name": "Papillary thyroid cancer"}, {"name": "Cardiofaciocutaneous syndrome"}],
    ),
    _build_gene(
        "ENSG00000169032", "MAPK1", "Mitogen-Activated Protein Kinase 1 (ERK2)", "22", 21754019, 21866916,
        "MAP激酶ERK2，MAPK/ERK信号通路的终端激酶。磷酸化胞质和核内多种底物，控制细胞增殖、分化、存活。在发育和癌变中关键。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "MAP kinase activity", "namespace": "molecular_function"},
            {"name": "regulation of ERK1 and ERK2 cascade", "namespace": "biological_process"},
            {"name": "cellular response to growth factor stimulus", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
            {"name": "cytosol", "namespace": "cellular_component"},
        ],
        [{"name": "MAPK signaling pathway", "pathway": "hsa04010"}, {"name": "Ras signaling pathway", "pathway": "hsa04014"}, {"name": "FoxO signaling pathway", "pathway": "hsa04068"}],
        [{"name": "Protein kinase domain", "accession": "PF00069"}],
        [],
    ),
    _build_gene(
        "ENSG00000170345", "FOS", "Fos Proto-Oncogene, AP-1 Transcription Factor Subunit", "14", 75278756, 75282230,
        "转录因子AP-1亚基c-Fos，与JUN二聚化形成AP-1复合物。是即刻早期基因，被MAPK信号快速诱导。调控增殖、分化、凋亡相关基因。",
        [
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "RNA polymerase II regulatory region DNA binding", "namespace": "molecular_function"},
            {"name": "response to growth factor", "namespace": "biological_process"},
            {"name": "cellular response to stress", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "MAPK signaling pathway", "pathway": "hsa04010"}, {"name": "Osteoclast differentiation", "pathway": "hsa04380"}, {"name": "Cellular senescence", "pathway": "hsa04218"}],
        [{"name": "bZIP transcription factor", "accession": "PF00170"}],
        [],
    ),
    _build_gene(
        "ENSG00000149554", "CHEK1", "Checkpoint Kinase 1", "11", 125625029, 125675443,
        "细胞周期检查点激酶CHK1，由ATR在DNA损伤或复制应激时激活。磷酸化CDC25磷酸酶使其降解，阻止CDK激活，实现细胞周期阻滞。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "DNA damage checkpoint", "namespace": "biological_process"},
            {"name": "DNA replication checkpoint", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Cell cycle", "pathway": "hsa04110"}, {"name": "p53 signaling pathway", "pathway": "hsa04115"}],
        [{"name": "Protein kinase domain", "accession": "PF00069"}],
        [],
    ),
    _build_gene(
        "ENSG00000165731", "RET", "Ret Proto-Oncogene", "10", 43077063, 43130363,
        "受体酪氨酸激酶RET，被GDNF家族配体激活。对肾脏发育和肠神经系统发育必需。体细胞激活突变导致甲状腺髓样癌。",
        [
            {"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"},
            {"name": "glial cell-derived neurotrophic factor receptor activity", "namespace": "molecular_function"},
            {"name": "nervous system development", "namespace": "biological_process"},
            {"name": "kidney development", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "Hirschsprung disease pathways"}, {"name": "Thyroid cancer", "pathway": "hsa05216"}],
        [{"name": "Cadherin-like", "accession": "PF00028"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Medullary thyroid carcinoma"}, {"name": "Multiple endocrine neoplasia type 2"}, {"name": "Hirschsprung disease"}],
    ),
    _build_gene(
        "ENSG00000160691", "SHH", "Sonic Hedgehog Signaling Molecule", "7", 155799980, 155812463,
        "分泌型信号分子Sonic Hedgehog，胚胎发育中关键的形态发生素。经自催化裂解和胆固醇修饰后，结合PTCH1解除对SMO的抑制，激活GLI转录因子。",
        [
            {"name": "morphogen activity", "namespace": "molecular_function"},
            {"name": "calcium ion binding", "namespace": "molecular_function"},
            {"name": "embryonic limb morphogenesis", "namespace": "biological_process"},
            {"name": "neural tube patterning", "namespace": "biological_process"},
            {"name": "extracellular space", "namespace": "cellular_component"},
        ],
        [{"name": "Hedgehog signaling pathway", "pathway": "hsa04340"}, {"name": "Basal cell carcinoma", "pathway": "hsa05217"}],
        [{"name": "Hedgehog N-terminal", "accession": "PF01085"}, {"name": "Hint domain", "accession": "PF13897"}],
        [{"name": "Holoprosencephaly"}, {"name": "Basal cell carcinoma"}, {"name": "Medulloblastoma"}],
    ),
    _build_gene(
        "ENSG00000143368", "CTNNB1", "Catenin Beta 1 (β-catenin)", "3", 41199873, 41240445,
        "β-catenin，Wnt信号通路核心转录共激活因子。在Wnt信号存在时稳定积累并入核，与TCF/LEF结合激活靶基因。也是cadherin黏附连接的组分。",
        [
            {"name": "DNA-binding transcription factor binding", "namespace": "molecular_function"},
            {"name": "cadherin binding", "namespace": "molecular_function"},
            {"name": "Wnt signaling pathway", "namespace": "biological_process"},
            {"name": "cell-cell adhesion", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
            {"name": "cell-cell adherens junction", "namespace": "cellular_component"},
        ],
        [{"name": "Wnt signaling pathway", "pathway": "hsa04310"}, {"name": "Hepatocellular carcinoma", "pathway": "hsa05225"}, {"name": "Adherens junction", "pathway": "hsa04520"}],
        [{"name": "Armadillo repeat", "accession": "PF00514"}],
        [{"name": "Colorectal cancer"}, {"name": "Hepatocellular carcinoma"}, {"name": "Medulloblastoma"}, {"name": "Desmoid tumor"}],
    ),
    _build_gene(
        "ENSG00000159216", "RUNX1", "RUNX Family Transcription Factor 1", "21", 36160067, 36421948,
        "造血转录因子AML1/RUNX1，CBF转录因子复合物的DNA结合亚基。造血干细胞生成和巨核细胞分化必需。在急性髓系白血病中常见易位(t(8;21))。",
        [
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "sequence-specific DNA binding", "namespace": "molecular_function"},
            {"name": "hematopoietic stem cell differentiation", "namespace": "biological_process"},
            {"name": "myeloid cell differentiation", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Transcriptional misregulation in cancer", "pathway": "hsa05202"}, {"name": "Acute myeloid leukemia", "pathway": "hsa05221"}],
        [{"name": "Runt domain", "accession": "PF00853"}],
        [{"name": "Acute myeloid leukemia (RUNX1-RUNX1T1 fusion)"}, {"name": "Familial platelet disorder with predisposition to AML"}],
    ),
    _build_gene(
        "ENSG00000136997", "MYC", "MYC Proto-Oncogene", "8", 127735434, 127741434,
        "转录因子c-Myc，与MAX二聚化后结合E-box元件。调控15%以上的人类基因组转录。控制细胞生长、增殖、代谢和核糖体生物合成。在大多数癌症中异常激活。",
        [
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "RNA polymerase II regulatory region DNA binding", "namespace": "molecular_function"},
            {"name": "positive regulation of cell population proliferation", "namespace": "biological_process"},
            {"name": "regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Pathways in cancer", "pathway": "hsa05200"}, {"name": "Transcriptional misregulation in cancer", "pathway": "hsa05202"}, {"name": "Cellular senescence", "pathway": "hsa04218"}],
        [{"name": "bHLH-MYC", "accession": "PF00010"}, {"name": "MYC leucine zipper", "accession": "PF02344"}],
        [{"name": "Burkitt lymphoma"}, {"name": "Multiple cancer types (gene amplification)"}, {"name": "Neuroblastoma"}],
    ),
    _build_gene(
        "ENSG00000165671", "NSD1", "Nuclear Receptor Binding SET Domain Protein 1", "5", 177206542, 177378172,
        "组蛋白甲基转移酶NSD1，催化H3K36单甲基化和二甲基化。调控发育基因和癌症相关基因的表达。Sotos综合征的致病基因。",
        [
            {"name": "histone methyltransferase activity (H3K36)", "namespace": "molecular_function"},
            {"name": "chromatin binding", "namespace": "molecular_function"},
            {"name": "regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "skeletal system development", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [],
        [{"name": "SET domain", "accession": "PF00856"}, {"name": "PHD finger", "accession": "PF00628"}, {"name": "PWWP domain", "accession": "PF00855"}],
        [{"name": "Sotos syndrome"}, {"name": "Beckwith-Wiedemann syndrome"}, {"name": "Acute myeloid leukemia (NSD1-NUP98 fusion)"}],
    ),
    _build_gene(
        "ENSG00000118046", "STK11", "Serine/Threonine Kinase 11 (LKB1)", "19", 1200488, 1227233,
        "肿瘤抑制蛋白LKB1，AMPK和AMPK相关激酶的上游激活激酶。控制细胞能量代谢、细胞极性和细胞周期。Peutz-Jeghers综合征的致病基因。",
        [
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "regulation of cell cycle", "namespace": "biological_process"},
            {"name": "cellular response to energy stress", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
            {"name": "cytoplasm", "namespace": "cellular_component"},
        ],
        [{"name": "AMPK signaling pathway", "pathway": "hsa04152"}, {"name": "mTOR signaling pathway", "pathway": "hsa04150"}],
        [{"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Peutz-Jeghers syndrome"}, {"name": "Non-small cell lung cancer"}, {"name": "Cervical cancer"}],
    ),
    _build_gene(
        "ENSG00000163930", "BAP1", "BRCA1 Associated Protein 1", "3", 52401830, 52410642,
        "去泛素化酶BAP1，核内DUB。BRCA1相互作用蛋白，参与染色质重塑、转录调控和DNA损伤应答。肿瘤抑制基因，突变见于间皮瘤等。",
        [
            {"name": "cysteine-type deubiquitinase activity", "namespace": "molecular_function"},
            {"name": "chromatin binding", "namespace": "molecular_function"},
            {"name": "DNA repair", "namespace": "biological_process"},
            {"name": "regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [],
        [{"name": "Ubiquitin C-terminal hydrolase", "accession": "PF00443"}, {"name": "BRCA1-associated protein C-terminal", "accession": "PF14840"}],
        [{"name": "Mesothelioma"}, {"name": "Uveal melanoma"}, {"name": "Tumor predisposition syndrome"}],
    ),
    _build_gene(
        "ENSG00000106799", "TGFBR1", "Transforming Growth Factor Beta Receptor 1", "9", 101898446, 101926962,
        "TGF-β I型受体ALK5。配体结合促使TGFBR2磷酸化TGFBR1，后者磷酸化SMAD2/3。调控细胞增殖、分化、凋亡和纤维化。",
        [
            {"name": "transforming growth factor beta receptor activity", "namespace": "molecular_function"},
            {"name": "protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "SMAD protein signal transduction", "namespace": "biological_process"},
            {"name": "positive regulation of epithelial to mesenchymal transition", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "TGF-beta signaling pathway", "pathway": "hsa04350"}, {"name": "Colorectal cancer", "pathway": "hsa05210"}, {"name": "Pancreatic cancer", "pathway": "hsa05212"}],
        [{"name": "TGF-beta receptor kinase", "accession": "PF07714"}, {"name": "GS domain", "accession": "PF08515"}],
        [{"name": "Loeys-Dietz syndrome"}, {"name": "Ferguson-Smith tumor"}],
    ),
    _build_gene(
        "ENSG00000125538", "IL6", "Interleukin 6", "7", 22725889, 22731520,
        "多效性细胞因子IL-6，由免疫细胞、成纤维细胞和肿瘤细胞分泌。激活JAK-STAT3通路，驱动炎症、免疫应答和癌症进展。",
        [
            {"name": "cytokine activity", "namespace": "molecular_function"},
            {"name": "interleukin-6 receptor binding", "namespace": "molecular_function"},
            {"name": "inflammatory response", "namespace": "biological_process"},
            {"name": "immune response", "namespace": "biological_process"},
            {"name": "extracellular space", "namespace": "cellular_component"},
        ],
        [{"name": "JAK-STAT signaling pathway", "pathway": "hsa04630"}, {"name": "Cytokine-cytokine receptor interaction", "pathway": "hsa04060"}],
        [{"name": "Interleukin-6/G-CSF/MGF family", "accession": "PF00489"}],
        [{"name": "Rheumatoid arthritis"}, {"name": "Castleman disease"}, {"name": "Cytokine release syndrome"}],
    ),
    _build_gene(
        "ENSG00000142453", "CARM1", "Coactivator Associated Arginine Methyltransferase 1", "19", 10865395, 10921524,
        "蛋白质精氨酸甲基转移酶CARM1/PRMT4，催化组蛋白H3多个精氨酸残基的不对称二甲基化。作为转录共激活因子，参与pre-mRNA剪接调控。",
        [
            {"name": "protein-arginine N-methyltransferase activity", "namespace": "molecular_function"},
            {"name": "histone methyltransferase activity", "namespace": "molecular_function"},
            {"name": "regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "positive regulation of gene expression", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [],
        [{"name": "Protein arginine methyltransferase", "accession": "PF05185"}],
        [],
    ),
    _build_gene(
        "ENSG00000134028", "ADAM10", "ADAM Metallopeptidase Domain 10", "15", 58600618, 58751340,
        "A Disintegrin and Metalloprotease 10，细胞表面脱落酶。切割Notch受体、APP、E-cadherin、EGFR配体等底物，调节信号通路。",
        [
            {"name": "metalloendopeptidase activity", "namespace": "molecular_function"},
            {"name": "Notch binding", "namespace": "molecular_function"},
            {"name": "Notch signaling pathway", "namespace": "biological_process"},
            {"name": "cell adhesion", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "Notch signaling pathway", "pathway": "hsa04330"}, {"name": "Alzheimer disease", "pathway": "hsa05010"}],
        [{"name": "ADAM metallopeptidase", "accession": "PF00200"}, {"name": "Disintegrin", "accession": "PF01562"}],
        [{"name": "Alzheimer disease"}, {"name": "Late-onset retinitis pigmentosa"}],
    ),
    _build_gene(
        "ENSG00000128342", "LIF", "LIF Interleukin 6 Family Cytokine", "22", 30216326, 30231973,
        "白血病抑制因子LIF，IL-6家族多效细胞因子。通过LIFR-gp130受体激活JAK-STAT3和MAPK通路。维持胚胎干细胞多能性，调控植入。",
        [
            {"name": "cytokine activity", "namespace": "molecular_function"},
            {"name": "growth factor activity", "namespace": "molecular_function"},
            {"name": "embryo implantation", "namespace": "biological_process"},
            {"name": "stem cell population maintenance", "namespace": "biological_process"},
            {"name": "extracellular space", "namespace": "cellular_component"},
        ],
        [{"name": "JAK-STAT signaling pathway", "pathway": "hsa04630"}, {"name": "Cytokine-cytokine receptor interaction", "pathway": "hsa04060"}],
        [{"name": "Interleukin-6/G-CSF/MGF family", "accession": "PF00489"}],
        [],
    ),
    _build_gene(
        "ENSG00000164362", "TERT", "Telomerase Reverse Transcriptase", "5", 1274409, 1327101,
        "端粒酶催化亚基，以自身RNA亚基为模板，在染色体末端合成端粒重复序列TTAGGG。维持端粒长度和细胞永生化。在90%以上癌症中被重新激活。",
        [
            {"name": "telomerase activity", "namespace": "molecular_function"},
            {"name": "RNA-directed DNA polymerase activity", "namespace": "molecular_function"},
            {"name": "telomere maintenance", "namespace": "biological_process"},
            {"name": "positive regulation of cell population proliferation", "namespace": "biological_process"},
            {"name": "telomerase holoenzyme complex", "namespace": "cellular_component"},
        ],
        [{"name": "Cellular senescence", "pathway": "hsa04218"}],
        [{"name": "Telomerase reverse transcriptase", "accession": "PF00078"}],
        [{"name": "Dyskeratosis congenita"}, {"name": "Idiopathic pulmonary fibrosis"}, {"name": "Multiple cancer types (promoter mutations)"}],
    ),
    _build_gene(
        "ENSG00000198947", "DMD", "Dystrophin", "X", 31119376, 33356917,
        "肌营养不良蛋白，连接细胞骨架F-actin和细胞外基质的Dystroglycan复合物。维持肌纤维膜在收缩过程中的结构稳定。人类最大的基因之一(2.2Mb)。",
        [
            {"name": "actin binding", "namespace": "molecular_function"},
            {"name": "dystroglycan binding", "namespace": "molecular_function"},
            {"name": "muscle contraction", "namespace": "biological_process"},
            {"name": "regulation of heart contraction", "namespace": "biological_process"},
            {"name": "dystrophin-associated glycoprotein complex", "namespace": "cellular_component"},
            {"name": "sarcolemma", "namespace": "cellular_component"},
        ],
        [{"name": "Arrhythmogenic right ventricular cardiomyopathy", "pathway": "hsa05412"}, {"name": "Dilated cardiomyopathy", "pathway": "hsa05414"}],
        [{"name": "Spectrin repeat", "accession": "PF00435"}, {"name": "WW domain", "accession": "PF00397"}, {"name": "ZZ domain", "accession": "PF00569"}, {"name": "Dystrophin C-terminal", "accession": "PF09068"}],
        [{"name": "Duchenne muscular dystrophy"}, {"name": "Becker muscular dystrophy"}, {"name": "Dilated cardiomyopathy"}],
    ),
    _build_gene(
        "ENSG00000111424", "VDR", "Vitamin D Receptor", "12", 47840981, 47905844,
        "维生素D受体，核受体超家族。被1,25-二羟维生素D3激活后调控钙稳态、骨矿化、免疫调节和细胞分化相关基因。",
        [
            {"name": "vitamin D receptor activity", "namespace": "molecular_function"},
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "calcium ion homeostasis", "namespace": "biological_process"},
            {"name": "bone mineralization", "namespace": "biological_process"},
            {"name": "immune response", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Mineral absorption", "pathway": "hsa04978"}, {"name": "Endocrine resistance", "pathway": "hsa01522"}],
        [{"name": "Nuclear hormone receptor", "accession": "PF00104"}],
        [{"name": "Vitamin D-dependent rickets type II"}, {"name": "Osteoporosis"}],
    ),
    _build_gene(
        "ENSG00000105810", "CDK6", "Cyclin Dependent Kinase 6", "7", 92608017, 92847457,
        "细胞周期蛋白依赖性激酶6，被D型Cyclin激活。磷酸化Rb蛋白释放E2F，驱动G1→S期转换。CDK4/6抑制剂是乳腺癌治疗药物。",
        [
            {"name": "cyclin-dependent protein serine/threonine kinase activity", "namespace": "molecular_function"},
            {"name": "cyclin binding", "namespace": "molecular_function"},
            {"name": "G1/S transition of mitotic cell cycle", "namespace": "biological_process"},
            {"name": "positive regulation of cell population proliferation", "namespace": "biological_process"},
            {"name": "cyclin-dependent protein kinase holoenzyme complex", "namespace": "cellular_component"},
        ],
        [{"name": "Cell cycle", "pathway": "hsa04110"}, {"name": "p53 signaling pathway", "pathway": "hsa04115"}, {"name": "Cellular senescence", "pathway": "hsa04218"}],
        [{"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Acute lymphoblastic leukemia"}, {"name": "Glioblastoma"}],
    ),
    _build_gene(
        "ENSG00000116062", "MSH6", "MutS Homolog 6", "2", 47695637, 47809392,
        "DNA错配修复蛋白MSH6，MutSα复合物的组分。识别单碱基错配和1-2bp插入/缺失。与MSH2形成异二聚体，启动错配修复。Lynch综合征致病基因。",
        [
            {"name": "mismatched DNA binding", "namespace": "molecular_function"},
            {"name": "ATP binding", "namespace": "molecular_function"},
            {"name": "mismatch repair", "namespace": "biological_process"},
            {"name": "maintenance of DNA repeat elements", "namespace": "biological_process"},
            {"name": "MutSalpha complex", "namespace": "cellular_component"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Mismatch repair", "pathway": "hsa03430"}, {"name": "Colorectal cancer", "pathway": "hsa05210"}],
        [{"name": "MutS mismatch repair", "accession": "PF01624"}],
        [{"name": "Lynch syndrome"}, {"name": "Endometrial cancer"}, {"name": "Colorectal cancer"}],
    ),
    _build_gene(
        "ENSG00000204252", "COL2A1", "Collagen Type II Alpha 1 Chain", "12", 47975354, 48006192,
        "II型胶原蛋白α1链，软骨的主要结构蛋白。形成三股螺旋纤维，为软骨提供抗张强度。突变导致多种软骨发育不良。",
        [
            {"name": "extracellular matrix structural constituent", "namespace": "molecular_function"},
            {"name": "platelet-derived growth factor binding", "namespace": "molecular_function"},
            {"name": "cartilage development", "namespace": "biological_process"},
            {"name": "skeletal system development", "namespace": "biological_process"},
            {"name": "extracellular matrix", "namespace": "cellular_component"},
        ],
        [{"name": "Protein digestion and absorption", "pathway": "hsa04974"}, {"name": "ECM-receptor interaction", "pathway": "hsa04512"}],
        [{"name": "Collagen triple helix repeat", "accession": "PF01391"}, {"name": "Fibrillar collagen C-terminal", "accession": "PF01410"}],
        [{"name": "Achondrogenesis type II"}, {"name": "Stickler syndrome"}, {"name": "Spondyloepiphyseal dysplasia"}],
    ),
    _build_gene(
        "ENSG00000135744", "AGT", "Angiotensinogen", "1", 230838269, 230850336,
        "血管紧张素原，肾素-血管紧张素系统的前体蛋白。被肾素切割生成AngI，进一步被ACE切割生成具有强效血管收缩活性的AngII。调控血压和水盐平衡。",
        [
            {"name": "serine-type endopeptidase inhibitor activity", "namespace": "molecular_function"},
            {"name": "hormone activity", "namespace": "molecular_function"},
            {"name": "regulation of blood pressure", "namespace": "biological_process"},
            {"name": "renin-angiotensin regulation of aldosterone production", "namespace": "biological_process"},
            {"name": "extracellular space", "namespace": "cellular_component"},
        ],
        [{"name": "Renin-angiotensin system", "pathway": "hsa04614"}, {"name": "Hypertension"}],
        [{"name": "Serpin", "accession": "PF00079"}],
        [{"name": "Hypertension"}, {"name": "Renal tubular dysgenesis"}],
    ),
    _build_gene(
        "ENSG00000109670", "FBXW7", "F-Box and WD Repeat Domain Containing 7", "4", 152695163, 152913659,
        "F-box蛋白FBXW7，SCF(FBXW7) E3泛素连接酶的底物识别亚基。靶向降解多种癌蛋白（Cyclin E, c-Myc, Notch, c-Jun, mTOR）。重要肿瘤抑制基因。",
        [
            {"name": "ubiquitin-protein transferase activity", "namespace": "molecular_function"},
            {"name": "phosphoprotein binding", "namespace": "molecular_function"},
            {"name": "protein ubiquitination", "namespace": "biological_process"},
            {"name": "negative regulation of cell population proliferation", "namespace": "biological_process"},
            {"name": "SCF ubiquitin ligase complex", "namespace": "cellular_component"},
        ],
        [{"name": "Ubiquitin mediated proteolysis", "pathway": "hsa04120"}, {"name": "Notch signaling pathway", "pathway": "hsa04330"}],
        [{"name": "F-box domain", "accession": "PF00646"}, {"name": "WD40 repeat", "accession": "PF00400"}],
        [{"name": "T-cell acute lymphoblastic leukemia"}, {"name": "Colorectal cancer"}, {"name": "Endometrial cancer"}],
    ),
    _build_gene(
        "ENSG00000177731", "FLT1", "Fms Related Receptor Tyrosine Kinase 1 (VEGFR1)", "13", 28300838, 28495807,
        "血管内皮生长因子受体1，结合VEGF-A、VEGF-B和PlGF。调控血管新生和血管通透性。可溶性剪接变体sFLT1作为VEGF trap参与子痫前期病理。",
        [
            {"name": "vascular endothelial growth factor receptor activity", "namespace": "molecular_function"},
            {"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"},
            {"name": "angiogenesis", "namespace": "biological_process"},
            {"name": "vascular endothelial growth factor signaling pathway", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "VEGF signaling pathway", "pathway": "hsa04370"}, {"name": "Pathways in cancer", "pathway": "hsa05200"}],
        [{"name": "Immunoglobulin-like domain", "accession": "PF00047"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Preeclampsia"}, {"name": "Hemangioma"}],
    ),
    _build_gene(
        "ENSG00000157404", "KIT", "KIT Proto-Oncogene, Receptor Tyrosine Kinase", "4", 54657918, 54740724,
        "干细胞因子受体c-Kit，III型受体酪氨酸激酶。造血干细胞、黑素细胞、生殖细胞和Cajal间质细胞发育必需。在胃肠间质瘤(GIST)中高频突变。",
        [
            {"name": "stem cell factor receptor activity", "namespace": "molecular_function"},
            {"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"},
            {"name": "hematopoietic stem cell proliferation", "namespace": "biological_process"},
            {"name": "pigmentation", "namespace": "biological_process"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "Pathways in cancer", "pathway": "hsa05200"}, {"name": "Ras signaling pathway", "pathway": "hsa04014"}, {"name": "Hematopoietic cell lineage", "pathway": "hsa04640"}],
        [{"name": "Immunoglobulin-like domain", "accession": "PF00047"}, {"name": "Protein kinase domain", "accession": "PF00069"}],
        [{"name": "Gastrointestinal stromal tumor (GIST)"}, {"name": "Mastocytosis"}, {"name": "Piebaldism"}, {"name": "Acute myeloid leukemia"}],
    ),
    _build_gene(
        "ENSG00000164171", "ITGA2", "Integrin Subunit Alpha 2", "5", 52947896, 53072544,
        "整合素α2亚基，与β1形成α2β1异二聚体（VLA-2）。主要胶原蛋白受体，介导细胞-细胞外基质粘附和信号传导。血小板胶原受体。",
        [
            {"name": "collagen binding", "namespace": "molecular_function"},
            {"name": "integrin binding", "namespace": "molecular_function"},
            {"name": "cell-matrix adhesion", "namespace": "biological_process"},
            {"name": "platelet activation", "namespace": "biological_process"},
            {"name": "integrin complex", "namespace": "cellular_component"},
            {"name": "plasma membrane", "namespace": "cellular_component"},
        ],
        [{"name": "Platelet activation", "pathway": "hsa04611"}, {"name": "ECM-receptor interaction", "pathway": "hsa04512"}, {"name": "Focal adhesion", "pathway": "hsa04510"}],
        [{"name": "Integrin alpha", "accession": "PF00357"}],
        [{"name": "Platelet glycoprotein Ia deficiency"}, {"name": "Thrombosis risk"}],
    ),
    _build_gene(
        "ENSG00000118513", "MYB", "MYB Proto-Oncogene, Transcription Factor", "6", 135181419, 135219173,
        "转录因子c-Myb，在造血干细胞和祖细胞中高表达。调控造血细胞增殖和分化。在白血病中常见异常激活（如MYB-NFIB融合）。",
        [
            {"name": "DNA-binding transcription factor activity", "namespace": "molecular_function"},
            {"name": "RNA polymerase II regulatory region DNA binding", "namespace": "molecular_function"},
            {"name": "hematopoietic progenitor cell differentiation", "namespace": "biological_process"},
            {"name": "positive regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "nucleus", "namespace": "cellular_component"},
        ],
        [{"name": "Transcriptional misregulation in cancer", "pathway": "hsa05202"}],
        [{"name": "Myb-like DNA-binding domain", "accession": "PF00249"}, {"name": "Myb C-terminal", "accession": "PF09316"}],
        [{"name": "Adenoid cystic carcinoma (MYB-NFIB fusion)"}, {"name": "T-cell acute lymphoblastic leukemia"}],
    ),
    _build_gene(
        "ENSG00000183765", "KMT2A", "Lysine Methyltransferase 2A (MLL1)", "11", 118336222, 118504463,
        "组蛋白甲基转移酶MLL1，MLL/SET1复合物催化核心。催化H3K4甲基化（转录激活标记）。通过HOX基因调控维持造血和胚胎发育。白血病原癌基因。",
        [
            {"name": "histone methyltransferase activity (H3K4)", "namespace": "molecular_function"},
            {"name": "chromatin binding", "namespace": "molecular_function"},
            {"name": "positive regulation of transcription by RNA polymerase II", "namespace": "biological_process"},
            {"name": "hematopoietic stem cell maintenance", "namespace": "biological_process"},
            {"name": "MLL1 complex", "namespace": "cellular_component"},
        ],
        [{"name": "Transcriptional misregulation in cancer", "pathway": "hsa05202"}, {"name": "Acute myeloid leukemia", "pathway": "hsa05221"}],
        [{"name": "SET domain", "accession": "PF00856"}, {"name": "PHD finger", "accession": "PF00628"}, {"name": "FY-rich", "accession": "PF05964"}],
        [{"name": "Acute leukemia (KMT2A rearrangements)"}, {"name": "Wiedemann-Steiner syndrome"}],
    ),
_build_gene(
        "XENO00000000001", "DraRadA", "Deinococcus radiodurans RadA", "Plasmid", 1000, 2000,
        "抗辐射双链断裂修复酶。拥有逆天的抗辐射能力，可在强伽马射线与火星宇宙射线中极速修复 DNA 双链断裂。",
        [{"name": "DNA repair", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "XENO00000000002", "SilA", "Silicatein-like A", "Synthetic", 1000, 2000,
        "硅代谢关键酶。二氧化硅聚合与矿化作用，能将环境中的游离硅酸盐沉积为坚硬的外骨骼，适合硅基生命设计。",
        [{"name": "Silicon metabolism", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "XENO00000000003", "SoxB", "Sulfur oxidation protein", "Plasmid", 1000, 2000,
        "无机硫氧化酶。通过氧化无机硫化物（如火星常见的硫酸盐）提供生长所需的化能动力，极端环境必备自养模块。",
        [{"name": "Sulfur metabolism", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "XENO00000000004", "MerR", "Mercuric resistance regulator", "Plasmid", 1000, 2000,
        "重金属汞抗性调节子。极强的高毒性重金属汞抗性，在岩浆或高硫矿床附近必备。",
        [{"name": "Mercury resistance", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "XENO00000000005", "GroEL", "Chaperonin GroEL", "Plasmid", 1000, 2000,
        "极端热休克伴侣蛋白。能在高温、高压、甚至硅酸盐溶剂中协助新生多肽链正确折叠，防止蛋白质变性失活。",
        [{"name": "Protein folding", "namespace": "biological_process"}], [], [], []
    ),
    # [通用] 核心管家基因、免疫系统与经典靶点 (General Biology Core)
    _build_gene(
        "ENSG00000111640", "GAPDH", "Glyceraldehyde-3-phosphate dehydrogenase", "12", 6534517, 6538371,
        "糖酵解途径核心代谢酶，最常用的管家基因(House-keeping gene)，维持细胞基础代谢。",
        [{"name": "glycolysis", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000075624", "ACTB", "Actin Beta", "7", 5527148, 5530601,
        "细胞骨架核心蛋白，维持细胞形态与运动，标准内参基因。",
        [{"name": "cytoskeleton organization", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000146648", "EGFR", "Epidermal Growth Factor Receptor", "7", 55086714, 55279321,
        "表皮生长因子受体，关键的细胞增殖调控靶点，非小细胞肺癌核心驱动基因。",
        [{"name": "transmembrane receptor protein tyrosine kinase activity", "namespace": "molecular_function"}], [], [], []
    ),
    _build_gene(
        "ENSG00000012048", "BRCA1", "BRCA1 DNA repair associated", "17", 43044295, 43125364,
        "乳腺癌易感基因，参与同源重组(HR)修复DNA双链断裂，维持基因组稳定性。",
        [{"name": "DNA repair", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000164305", "CASP3", "Caspase 3", "4", 184511270, 184533729,
        "细胞凋亡(Apoptosis)途径的核心执行蛋白酶。",
        [{"name": "apoptotic process", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000136244", "IL6", "Interleukin 6", "7", 22725889, 22732002,
        "核心促炎细胞因子，参与免疫反应、急性期反应和造血调控。",
        [{"name": "immune response", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000198900", "CD4", "CD4 Molecule", "12", 6766629, 6799042,
        "T辅助细胞表面标志物，MHC II类分子共受体，免疫系统核心枢纽。",
        [{"name": "T cell activation", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000153563", "CD8A", "CD8a Molecule", "2", 86930000, 86950000,
        "细胞毒性T细胞标志物，介导抗肿瘤与抗病毒免疫杀伤。",
        [{"name": "adaptive immune response", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000141736", "ERBB2", "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)", "17", 39695000, 39745000,
        "重要的乳腺癌与胃癌靶点，促进细胞过度增殖。",
        [{"name": "cell proliferation", "namespace": "biological_process"}], [], [], []
    ),
    _build_gene(
        "ENSG00000198793", "MTOR", "Mechanistic Target Of Rapamycin Kinase", "1", 11100000, 11200000,
        "细胞生长和代谢的中央调控枢纽，感应营养和能量状态。",
        [{"name": "regulation of cell growth", "namespace": "biological_process"}], [], [], []
    ),
]

SEED_DOMAINS: list[ProteinDomain] = [
    _build_domain("PF00069", "PF00069", "Protein kinase domain", "Eukaryotic protein kinase catalytic domain. Transfers phosphate from ATP to serine/threonine or tyrosine residues.", "Pfam"),
    _build_domain("PF07714", "PF07714", "Receptor tyrosine kinase", "Tyrosine kinase domain found in receptor tyrosine kinases. Includes EGFR, KIT, FLT1, RET, ERBB2.", "Pfam"),
    _build_domain("PF00104", "PF00104", "Nuclear hormone receptor ligand-binding domain", "Ligand-binding domain of nuclear hormone receptors. Includes estrogen, androgen, vitamin D, and thyroid hormone receptors.", "Pfam"),
    _build_domain("PF00870", "PF00870", "P53 DNA-binding domain", "Central DNA-binding domain of tumor suppressor p53. Recognizes p53 response elements.", "Pfam"),
    _build_domain("PF00071", "PF00071", "Ras GTPase", "Ras family small GTPases. Molecular switch cycling between active GTP-bound and inactive GDP-bound states.", "Pfam"),
    _build_domain("PF00853", "PF00853", "Runt domain", "DNA-binding domain of RUNX transcription factors. Forms heterodimer with CBFβ.", "Pfam"),
    _build_domain("PF00514", "PF00514", "Armadillo repeat", "Tandem repeat forming superhelix for protein-protein interactions. Found in β-catenin and importin-α.", "Pfam"),
    _build_domain("PF00634", "PF00634", "BRCA2 repeat (BRC)", "BRC repeats in BRCA2 that bind RAD51 recombinase for homologous recombination.", "Pfam"),
    _build_domain("PF00856", "PF00856", "SET domain", "Histone lysine methyltransferase catalytic domain. Methylates H3K4, H3K9, H3K27, H3K36, or H4K20.", "Pfam"),
    _build_domain("PF00628", "PF00628", "PHD finger", "Plant Homeodomain zinc finger. Reads histone methylation marks (H3K4me3) and regulates chromatin.", "Pfam"),
    _build_domain("PF01085", "PF01085", "Hedgehog N-terminal signaling domain", "N-terminal domain of Hedgehog morphogens after autoproteolytic cleavage and cholesterol modification.", "Pfam"),
    _build_domain("PF00170", "PF00170", "bZIP transcription factor", "Basic leucine zipper domain. Dimerizes and binds DNA. Found in FOS, JUN, CREB, ATF families.", "Pfam"),
    _build_domain("PF00435", "PF00435", "Spectrin repeat", "Triple-helical bundle repeat. Found in dystrophin, spectrin, and α-actinin for structural flexibility.", "Pfam"),
    _build_domain("PF00097", "PF00097", "RING finger domain", "Zinc-binding domain with E3 ubiquitin ligase activity. Found in BRCA1, TRIM proteins, MDM2.", "Pfam"),
    _build_domain("PF00533", "PF00533", "BRCA1 C-terminal (BRCT) domain", "Phospho-protein binding domain in DNA damage response proteins. Tandem BRCT in BRCA1.", "Pfam"),
    _build_domain("PF01391", "PF01391", "Collagen triple helix repeat", "Gly-X-Y tripeptide repeat forming collagen triple helix. Provides tensile strength to ECM.", "Pfam"),
    _build_domain("PF00400", "PF00400", "WD40 repeat", "Beta-propeller scaffold domain mediating protein-protein interactions. Found in FBXW7, CDC20, WDR5.", "Pfam"),
    _build_domain("PF00646", "PF00646", "F-box domain", "Substrate recognition domain of SCF E3 ubiquitin ligases. Binds SKP1 to link substrates to ubiquitination machinery.", "Pfam"),
    _build_domain("PF00047", "PF00047", "Immunoglobulin-like domain", "Ig-like fold found in cell adhesion molecules, immune receptors, and growth factor receptors.", "Pfam"),
    _build_domain("PF00010", "PF00010", "Helix-loop-helix DNA-binding domain", "bHLH domain mediating dimerization and DNA binding. Found in MYC, MAX, MYOD.", "Pfam"),
    _build_domain("PF00489", "PF00489", "Interleukin-6/G-CSF/MGF family", "Four-helix bundle cytokine family. Includes IL-6, LIF, G-CSF, and OSM.", "Pfam"),
    _build_domain("PF00357", "PF00357", "Integrin alpha cytoplasmic region", "Cytoplasmic domain of integrin alpha subunits. Mediates inside-out signaling.", "Pfam"),
    _build_domain("PF00078", "PF00078", "Reverse transcriptase (RNA-dependent DNA polymerase)", "Catalytic domain of reverse transcriptases. Found in telomerase (TERT) and retroviral RT.", "Pfam"),
    _build_domain("PF00249", "PF00249", "Myb-like DNA-binding domain", "Helix-turn-helix DNA-binding domain found in MYB transcription factors.", "Pfam"),
    _build_domain("PF00200", "PF00200", "Disintegrin domain", "Cysteine-rich domain in ADAM metalloproteases. Mediates integrin binding.", "Pfam"),
    _build_domain("PF01562", "PF01562", "Reprolysin family metalloprotease (ADAM)", "Zinc-dependent metalloprotease catalytic domain in ADAM family.", "Pfam"),
    _build_domain("PF05185", "PF05185", "Protein arginine N-methyltransferase", "PRMT family catalytic domain. Transfers methyl group from SAM to arginine.", "Pfam"),
    _build_domain("PF00443", "PF00443", "Ubiquitin carboxyl-terminal hydrolase", "Deubiquitinase (DUB) catalytic domain. Cleaves ubiquitin from substrates. Found in BAP1.", "Pfam"),
    _build_domain("PF01624", "PF01624", "MutS DNA mismatch repair domain", "ATP-binding and DNA-mismatch recognition domain in MutS homologs (MSH2, MSH6).", "Pfam"),
    _build_domain("PF02259", "PF02259", "FAT domain", "FRAP-ATM-TRRAP domain. Scaffold domain in mTOR and ATM/ATR kinases.", "Pfam"),
]


SEED_PATHWAYS: list[PathwayRecord] = [
    _build_pathway("hsa04010", "MAPK signaling pathway", "RAS-RAF-MEK-ERK/JNK/p38 cascades controlling proliferation, differentiation, apoptosis, and stress response.", ["KRAS", "BRAF", "MAPK1", "FOS"]),
    _build_pathway("hsa04151", "PI3K-Akt signaling pathway", "PI3K/AKT/mTOR pathway activated by growth factors, regulating cell growth, survival, and metabolism.", ["PIK3CA", "AKT1", "MTOR", "EGFR", "ERBB2"]),
    _build_pathway("hsa04014", "Ras signaling pathway", "RAS small GTPase signaling controlling cell proliferation, differentiation, and survival.", ["KRAS", "BRAF", "KIT"]),
    _build_pathway("hsa04150", "mTOR signaling pathway", "Nutrient and growth factor sensing pathway controlling protein synthesis, autophagy, and metabolism.", ["MTOR", "AKT1", "PIK3CA", "STK11"]),
    _build_pathway("hsa04110", "Cell cycle", "Cyclin-CDK driven cell cycle progression from G1 through M phase with checkpoint controls.", ["TP53", "CDK6", "CHEK1"]),
    _build_pathway("hsa04115", "p53 signaling pathway", "DNA damage response, cell cycle arrest, apoptosis, and senescence orchestrated by p53.", ["TP53", "CDK6", "CHEK1"]),
    _build_pathway("hsa04210", "Apoptosis", "Programmed cell death through intrinsic (mitochondrial) and extrinsic (death receptor) pathways.", ["TP53"]),
    _build_pathway("hsa04218", "Cellular senescence", "Stable cell cycle arrest in response to telomere shortening, DNA damage, or oncogene activation.", ["TP53", "CDK6", "TERT", "MYC"]),
    _build_pathway("hsa04140", "Autophagy", "Lysosomal degradation pathway for cellular components. Regulated by mTOR and AMPK.", ["MTOR"]),
    _build_pathway("hsa04152", "AMPK signaling pathway", "Energy sensor AMPK pathway activated by low ATP. Promotes catabolism and inhibits anabolism.", ["MTOR", "STK11"]),
    _build_pathway("hsa04350", "TGF-beta signaling pathway", "SMAD-dependent and independent signaling controlling growth inhibition, EMT, and fibrosis.", ["TGFBR1"]),
    _build_pathway("hsa04330", "Notch signaling pathway", "Cell-cell communication controlling cell fate decisions, stemness, and lateral inhibition.", ["ADAM10"]),
    _build_pathway("hsa04310", "Wnt signaling pathway", "β-catenin dependent and independent pathways controlling development, stem cells, and oncogenesis.", ["CTNNB1"]),
    _build_pathway("hsa04340", "Hedgehog signaling pathway", "SHH-PTCH1-SMO-GLI morphogen pathway controlling embryonic patterning and tissue homeostasis.", ["SHH"]),
    _build_pathway("hsa04630", "JAK-STAT signaling pathway", "Cytokine receptor signaling through JAK kinases and STAT transcription factors.", ["IL6", "LIF"]),
    _build_pathway("hsa04060", "Cytokine-cytokine receptor interaction", "Ligand-receptor pairs for cytokines, chemokines, and growth factors.", ["IL6", "LIF"]),
    _build_pathway("hsa03440", "Homologous recombination", "High-fidelity DNA double-strand break repair using homologous template.", ["BRCA1", "BRCA2"]),
    _build_pathway("hsa03430", "Mismatch repair", "Post-replicative correction of base-base mismatches and insertion/deletion loops.", ["MSH6"]),
    _build_pathway("hsa03460", "Fanconi anemia pathway", "Interstrand crosslink repair pathway coordinating multiple DNA repair mechanisms.", ["BRCA1", "BRCA2"]),
    _build_pathway("hsa01521", "EGFR tyrosine kinase inhibitor resistance", "Mechanisms of resistance to EGFR-targeted therapy including bypass signaling.", ["EGFR", "ERBB2", "PIK3CA"]),
    _build_pathway("hsa04120", "Ubiquitin mediated proteolysis", "Ubiquitin-proteasome system controlling protein degradation through E1-E2-E3 cascade.", ["FBXW7"]),
    _build_pathway("hsa05200", "Pathways in cancer", "Integrated cancer signaling network including RTK-RAS-PI3K and cell cycle/apoptosis.", ["TP53", "KRAS", "PIK3CA", "EGFR", "ERBB2", "MYC", "BRAF", "KIT"]),
    _build_pathway("hsa04380", "Osteoclast differentiation", "RANKL-RANK-NFATc1 signaling driving bone-resorbing osteoclast formation.", ["FOS"]),
    _build_pathway("hsa04068", "FoxO signaling pathway", "FOXO transcription factor regulation by AKT phosphorylation controlling stress resistance and metabolism.", ["AKT1", "MAPK1"]),
    _build_pathway("hsa04614", "Renin-angiotensin system", "Blood pressure and fluid/electrolyte homeostasis through angiotensin cascade.", ["AGT"]),
    _build_pathway("hsa04370", "VEGF signaling pathway", "Endothelial cell signaling controlling angiogenesis, vascular permeability, and lymphangiogenesis.", ["FLT1"]),
    _build_pathway("hsa04611", "Platelet activation", "Signaling cascade from platelet adhesion to aggregation and thrombus formation.", ["ITGA2"]),
    _build_pathway("hsa04510", "Focal adhesion", "Integrin-mediated cell-matrix adhesion complexes linked to actin cytoskeleton and signaling.", ["ITGA2"]),
    _build_pathway("hsa04512", "ECM-receptor interaction", "Cell surface receptors binding extracellular matrix proteins including collagens and laminins.", ["ITGA2", "COL2A1"]),
    _build_pathway("hsa04520", "Adherens junction", "Cadherin-catenin cell-cell adhesion complexes linking to actin cytoskeleton.", ["CTNNB1"]),
    _build_pathway("hsa04915", "Estrogen signaling pathway", "Nuclear and membrane estrogen receptor signaling controlling female physiology.", ["ESR1"]),
    _build_pathway("hsa05215", "Prostate cancer", "AR signaling and PTEN loss driving prostate adenocarcinoma progression.", ["AR"]),
    _build_pathway("hsa04910", "Insulin signaling pathway", "Metabolic and mitogenic signaling downstream of the insulin receptor.", ["AKT1"]),
    _build_pathway("hsa05225", "Hepatocellular carcinoma", "Wnt/β-catenin, p53, and telomerase alterations in liver cancer.", ["CTNNB1"]),
    _build_pathway("hsa04640", "Hematopoietic cell lineage", "Differentiation hierarchy from hematopoietic stem cells to mature blood cells.", ["KIT"]),
    _build_pathway("hsa04978", "Mineral absorption", "Intestinal absorption and renal reabsorption of calcium, iron, and other minerals.", ["VDR"]),
    _build_pathway("hsa01522", "Endocrine resistance", "Mechanisms of resistance to hormone therapy in breast and prostate cancers.", ["VDR"]),
]


SEED_ONTOLOGY_NODES: list[OntologyNode] = [
    # 宏观生物过程拓扑 (GO Biological Process)
    OntologyNode("GO:0008152", "metabolic process", "GO_BP", "Chemical reactions and pathways, including anabolism and catabolism.", None),
    OntologyNode("GO:0005975", "carbohydrate metabolic process", "GO_BP", "Metabolism of carbohydrates.", "GO:0008152"),
    OntologyNode("GO:0006096", "glycolytic process", "GO_BP", "Glycolysis pathway.", "GO:0005975"),
    
    OntologyNode("GO:0006950", "response to stress", "GO_BP", "A change in state or activity of a cell or an organism as a result of a stress stimulus.", None),
    OntologyNode("GO:0006281", "DNA repair", "GO_BP", "The process of restoring DNA after damage.", "GO:0006950"),
    OntologyNode("GO:0009314", "response to radiation", "GO_BP", "Response to ionizing/UV radiation.", "GO:0006950"),
    OntologyNode("GO:0009266", "response to temperature stimulus", "GO_BP", "Response to hot or cold stress.", "GO:0006950"),
    
    OntologyNode("GO:0007165", "signal transduction", "GO_BP", "Cellular process in which a signal is conveyed to trigger a change.", None),
    OntologyNode("GO:0008283", "cell proliferation", "GO_BP", "Multiplication or reproduction of cells.", None),
    OntologyNode("GO:0006915", "apoptotic process", "GO_BP", "Programmed cell death.", None),

    # 分子功能拓扑 (GO Molecular Function)
    OntologyNode("GO:0003824", "catalytic activity", "GO_MF", "Catalysis of a biochemical reaction.", None),
    OntologyNode("GO:0016301", "kinase activity", "GO_MF", "Catalysis of the transfer of a phosphate group.", "GO:0003824"),
    OntologyNode("GO:0004871", "signal transducer activity", "GO_MF", "Mediates the transfer of a signal from the outside to the inside of a cell.", None),
    OntologyNode("GO:0004888", "transmembrane receptor activity", "GO_MF", "Receptor that spans the membrane.", "GO:0004871"),

    # 疾病拓扑 (OpenTargets MONDO)
    OntologyNode("MONDO:0045024", "cancer", "DISEASE", "A disease characterized by uncontrolled cellular proliferation.", None),
    OntologyNode("MONDO:0008903", "lung cancer", "DISEASE", "A malignant neoplasm involving the lung.", "MONDO:0045024"),
    OntologyNode("MONDO:0007254", "breast cancer", "DISEASE", "A primary malignant neoplasm of the breast.", "MONDO:0045024"),
    OntologyNode("MONDO:0018901", "glioblastoma", "DISEASE", "A fast-growing, aggressive type of central nervous system tumor that forms on the supportive tissue of the brain.", "MONDO:0045024"),
    OntologyNode("MONDO:0004992", "neurodegenerative disease", "DISEASE", "A disease caused by progressive loss of structure or function of neurons.", None),

    # 异种/极端环境拓扑 (Xeno / Extreme Env)
    OntologyNode("ENV:EXTREME", "Extreme Environment", "EXTREME_ENV", "Environments with extreme physical or chemical conditions.", None),
    OntologyNode("ENV:EXT_RAD", "High Radiation", "EXTREME_ENV", "Environments with high levels of ionizing radiation (e.g. Mars surface).", "ENV:EXTREME"),
    OntologyNode("ENV:EXT_THERM", "High Temperature", "EXTREME_ENV", "Geothermal or magma environments (> 100C).", "ENV:EXTREME"),
    OntologyNode("ENV:EXT_CHEM", "Toxic Chemical", "EXTREME_ENV", "Environments rich in toxic chemicals like arsenic, mercury, or sulfuric acid.", "ENV:EXTREME"),
]

def seed_database(gene_db: GeneDatabase) -> dict[str, Any]:
    gene_db.insert_genes(SEED_GENES)
    gene_db.insert_domains(SEED_DOMAINS)
    gene_db.insert_pathways(SEED_PATHWAYS)
    gene_db.insert_ontology_nodes(SEED_ONTOLOGY_NODES)
    return {
        "genes_seeded": len(SEED_GENES),
        "domains_seeded": len(SEED_DOMAINS),
        "pathways_seeded": len(SEED_PATHWAYS),
        "ontology_nodes_seeded": len(SEED_ONTOLOGY_NODES),
        "total_genes_in_db": gene_db.gene_count(),
        "total_domains_in_db": gene_db.domain_count(),
        "total_pathways_in_db": gene_db.pathway_count(),
    }
